### PR TITLE
Refactoring2

### PR DESCRIPTION
**Pull request by ar2rworld**
Squashed commits from #4

### CODE REVIEW

**Comment by umputun** [comment]
If you are going to work on this one, place close #4.

In case you have troubles to resolve the conflict, let me know, and I'll do it.

**Comment by ar2rworld** [comment]
force pushed squashed commits here and closed #4

**Comment by umputun** [comment]
Looking better. I'll merge and will take a closer look later.

**Comment by umputun** [comment]
looks like some files from .github were accidentally moved to the root. I have committed a fix for this as well as properly grouped the go.mod.

**Pull request merged**
